WP-586: Improve Field().retrieve() Performance
QuicketSolutions/pydal pull request #1
Opened 2019-05-08 19:08 UTC by timm3

Only fetch fields necessary for data retrieval instead of the entire record.

2019-05-08 19:59 UTC, bhchance approved these changes

2019-05-09 01:41 UTC, john-pierce requested changes
Won't this give a `KeyError:` in the `authorize` case if updatefield is a bool or not a string?

I'm unsure what the behavior would have been prior because the resulting query would be `SELECT * ...` but it will definitely cause problems if this isn't accounted for now.

2019-05-09 17:35 UTC, timm3 commented
@john-pierce good catch. I'm looking into it.

2019-05-09 21:50 UTC, john-pierce approved these changes

2019-05-10 19:37 UTC, merged